# Generated by Django 5.2.5 on 2025-09-01 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='estimated_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='spent_time',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='duration',
        ),
    ]
