# Generated by Django 5.2.5 on 2025-09-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0002_remove_task_estimated_time_remove_task_spent_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_time',
            field=models.IntegerField(blank=True, help_text='Estimated time in minutes format', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='spent_time',
            field=models.IntegerField(default=0, help_text='Total time spent on this task in minutes'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
